version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: api_comments
    restart: unless-stopped
    working_dir: /var/www/api_comments
    tty: true
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./app:/var/www/api_comments
    ports:
      - "9001:9000"
    networks:
      - api_comments

  mysql:
    image: mysql:5.7
    container_name: api_comments_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: api_comments
      MYSQL_USER: api_comments
      MYSQL_PASSWORD: api_comments
      MYSQL_ROOT_PASSWORD: api_comments
    networks:
      - api_comments

  mysql-test:
    image: mysql:5.7
    container_name: api_comments_mysql_test
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33063:3306"
    environment:
      MYSQL_DATABASE: api_comments
      MYSQL_USER: api_comments
      MYSQL_PASSWORD: api_comments
      MYSQL_ROOT_PASSWORD: api_comments
    networks:
      - api_comments

  nginx:
    image: nginx:alpine
    container_name: api_comments_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/api_comments
    depends_on:
      - app
    networks:
      - api_comments

  redis:
    image: redis:alpine
    container_name: api_comments_redis
    restart: unless-stopped
    ports:
      - "63791:6379"
    networks:
      - api_comments

  npm:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: api_comments_npm
    restart: unless-stopped
    volumes:
      - ./app:/var/www/api_comments
    networks:
      - api_comments

networks:
  api_comments: